### ISSUE TITLE
deprecated issue

### ISSUE THREAD

**Issue by changhuaxu** [Oneflow-Inc/community#4]
deprecated

**Comment by Flowingsun007** [comment]
主题可以加个：megatron模型/流水并行

**Comment by yuanms2** [comment]
主题 可以配合我们产品的发布节奏，譬如我们计划要发布GPT-3 了，可以组织几次关于训练大模型的讨论；等我们要发布PyTorch易用性了，可以组织几次关于动态图，eager mode，autograd的，这些问题我们在研发过程都做过调研了。 到时候想办法引导，变成是社群自己提出来的感兴趣的话题。

**Comment by changhuaxu** [comment]
> 主题可以加个：megatron模型/流水并行



> 主题 可以配合我们产品的发布节奏，譬如我们计划要发布GPT-3 了，可以组织几次关于训练大模型的讨论；等我们要发布PyTorch易用性了，可以组织几次关于动态图，eager mode，autograd的，这些问题我们在研发过程都做过调研了。 到时候想办法引导，变成是社群自己提出来的感兴趣的话题。

几个思路可以供参考：
我们根据gpt-3的进度情况来定时间计划
大主题就围绕“大模型的训练方法分析与比较”
子议题先介绍一下megatron、deepspeed等等，最后讲oneflow训练gpt-3的经验与方法

**Comment by doombeaker** [comment]
我建议现在重点要讨论是今年第一期的 meetup 要怎么做的 【细节规划】。

因为既然是是试水，就没有必要展开太广讨论议题征集，因为：
  1. 这个活动希望是开源爱好者导向，而不是 OneFlow 导向，我们讨论的议题可能会根据参与者的要求修改
  2. 第一期做完后，肯定有要复盘和迭代的事情，这里面也可能会推翻试水阶段定下的议题

我觉得可以先讨论下：
  1. meetup 开始前，让参与者可以做那些准备工作，让现场效果更好
  2. 议题演讲者，要做那些准备工作、时间节点，保证现场效果不翻车
