### ISSUE TITLE
社区技术资料库的构思

### ISSUE THREAD

**Issue by changhuaxu** [Oneflow-Inc/community#8]

**Comment by jackalcooper** [comment]
你可以做个github pages把他们整合起来，https://pages.github.com
然后我们把域名换成oneflow的

**Comment by doombeaker** [comment]
这个 community 仓库是 public 的，所有互联网用户都可以访问哈（包括看到这个 issue）。

**Comment by changhuaxu** [comment]
文档里列出的内容也都是public的。
出发点是把社区用的用户和开发者，都当成新同事一样的对待，通过一个持续更新、完善的文档资料库，帮助他们很方便地找到需要的文档。

**Comment by Wang-Jinxu** [comment]
现有的内容基本上不是纵深逻辑，按现有的内容进行层级“进阶”是有问题的

**Comment by changhuaxu** [comment]
一并回复一下：
1、开会讨论的时候预期是按层次递进的，但是整理下来发现输出的内容并不是层次递进的，pr的时候已经调整了二级标题，issue还没修改。
2、素材整理是必须要做的一件事情，汇总历史文档的library能够帮助社区在认知、学习oneflow的过程中有更好的体验。
3、library.md已经提交了pr，或许次级标题的描述和内容归类有些不恰当的地方，与其点评一二三四，不如先approve第一版，再提修改的pr。
